apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app-deploy
  labels:
    app: healthcare-app-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app-app
  template:
    metadata:
      labels:
        app: healthcare-app-app
    spec:
      containers:
      - name: healthcare-app-container
        image: junaidm3699/healthcare-eta-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-np-service
  labels:
    app: healthcare-app-app
spec:
  selector:
    app: healthcare-app-app

  type: NodePort
  ports:
  - nodePort: 31055    
    port: 8082
    targetPort: 8082
